import Head from 'next/head'
import {DateInput} from '@alfalab/core-components/date-input';
import {Select} from '@alfalab/core-components/select';
import {PickerButtonDesktop} from '@alfalab/core-components/picker-button/desktop';

export default function Home() {

    const options = [
        {key: '1', content: 'Neptunium'},
        {key: '2', content: 'Plutonium'},
        {key: '3', content: 'Americium'},
        {key: '4', content: 'Curium'},
        {key: '5', content: 'Berkelium'},
        {key: '6', content: 'Californium'},
        {key: '7', content: 'Einsteinium'},
        {key: '8', content: 'Fermium'},
    ];

    const optionsPicker = [{key: 'Car'}, {key: 'Star'}, {key: 'Flower'}, {key: 'Banknote'}];

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <DateInput label='Дата зимнего солнцестояния' size='m'/>
                <div style={{height: 'var(--gap-m)'}}/>
                <PickerButtonDesktop options={optionsPicker} view='primary' label='Picker button'/>
                <div style={{height: 'var(--gap-m)'}}/>
                <Select
                    allowUnselect={true}
                    size='m'
                    options={options}
                    placeholder='Одиночный выбор'
                    block={true}
                />
                <div style={{height: 'var(--gap-m)'}}/>
                <Select
                    allowUnselect={true}
                    size='m'
                    options={options}
                    placeholder='Множественный выбор'
                    multiple={true}
                    block={true}
                />
            </main>
        </>
    )
}
